### ISSUE TITLE
Error running 1.0.1 with NPX

### ISSUE THREAD

**Issue by RangerMauve** [martinheidegger/network-interfaces#4]
Windows 10
v11.9.0
npm 6.5.0

```
npx @leichtgewicht/network-interfaces
npx: installed 9 in 4.791s
Cannot read property 'emit' of undefined
C:\Users\Mauve\AppData\Roaming\npm-cache\_npx\21816\node_modules\@leichtgewicht\network-interfaces\index.js:38
      this.emit('warning', Object.assign(new Error(`Multiple network addresses with same key detected ${key}`), {
           ^

TypeError: Cannot read property 'emit' of undefined
    at collectAddresses (C:\Users\Mauve\AppData\Roaming\npm-cache\_npx\21816\node_modules\@leichtgewicht\network-interfaces\index.js:38:12)
    at collectAddresses.next (<anonymous>)
    at NetworkInterfaces._update (C:\Users\Mauve\AppData\Roaming\npm-cache\_npx\21816\node_modules\@leichtgewicht\network-interfaces\index.js:214:18)
    at getActive (C:\Users\Mauve\AppData\Roaming\npm-cache\_npx\21816\node_modules\@leichtgewicht\network-interfaces\index.js:173:14)
    at wmic.get_value (C:\Users\Mauve\AppData\Roaming\npm-cache\_npx\21816\node_modules\@leichtgewicht\network-interfaces\get-active\win32.js:8:5)
    at Object.callback (C:\Users\Mauve\AppData\Roaming\npm-cache\_npx\21816\node_modules\@leichtgewicht\network-interfaces\node_modules\wmic\index.js:245:7)
    at C:\Users\Mauve\AppData\Roaming\npm-cache\_npx\21816\node_modules\@leichtgewicht\network-interfaces\node_modules\async\dist\async.js:2271:31
    at C:\Users\Mauve\AppData\Roaming\npm-cache\_npx\21816\node_modules\@leichtgewicht\network-interfaces\node_modules\async\dist\async.js:969:16
    at C:\Users\Mauve\AppData\Roaming\npm-cache\_npx\21816\node_modules\@leichtgewicht\network-interfaces\node_modules\wmic\index.js:220:9
    at C:\Users\Mauve\AppData\Roaming\npm-cache\_npx\21816\node_modules\@leichtgewicht\network-interfaces\node_modules\async\dist\async.js:3888:9

C:\Users\Mauve\programming\dat>
```

**Comment by martinheidegger** [comment]
@RangerMauve can you have a look at #5

**Comment by martinheidegger** [comment]
It should be fixed now but emit a warning. It would help me if you could let me know what `node -p "os.networkInterfaces()"` returns on your computer.

**Comment by RangerMauve** [comment]
Don't use this for evil. :P

`removed for privacy`

**Comment by martinheidegger** [comment]
Thank you! Seems like I need to re-evaluate how I identify addresses. See #5
